spring.datasource.url=jdbc:mysql://localhost:3306/brewhaven
spring.datasource.username=root
spring.datasource.password=jyoti2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080
razorpay.key.id=rzp_test_T7fMXIEtzyb7vF
razorpay.key.secret=I7iz6Att7dSIPL9ao4zNsbmt

# ================= EMAIL =================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jyotibairagi2164@gmail.com
spring.mail.password=wltwamtnraiusfle
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true